### ISSUE TITLE
Brother can we implement same in for live market data, given  by fyers

### ISSUE THREAD

**Issue by raviyellani** [PraneshBalekai/algotrade_intraday_momentum#1]
Can we get the momentum from live market data provided by fyers

**Comment by PraneshBalekai** [comment]
Check out the .csv files used in this strategy under `strategies/st_int_mom_data` . It only requires daily OHLC prices, I'm sure you can get it from any data provider. Although, you will need historical data (~up to 90 days), not just live market data.
